<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="7" hostname="PUN-WKS-AC422" name="com.testcases.LoginPageTest" tests="8" failures="0" timestamp="02 Apr 2019 04:35:41 GMT" time="0.001" errors="1">
  <testcase name="linkedInLinkTest" time="0.000" classname="com.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- linkedInLinkTest -->
  <testcase name="setup" time="0.001" classname="com.testcases.LoginPageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.base.TestBase.initialization(TestBase.java:42)
at com.testcases.LoginPageTest.setup(LoginPageTest.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setup -->
  <testcase name="validatImageTest" time="0.000" classname="com.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- validatImageTest -->
  <testcase name="twitterLinkTest" time="0.000" classname="com.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- twitterLinkTest -->
  <testcase name="loginPageTitleTest" time="0.000" classname="com.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <testcase name="fbLinkTest" time="0.000" classname="com.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- fbLinkTest -->
  <testcase name="loginTest" time="0.000" classname="com.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="youtubeLinkTest" time="0.000" classname="com.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- youtubeLinkTest -->
</testsuite> <!-- com.testcases.LoginPageTest -->
